version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Adjust if your `package.json` is in a subdirectory
    schedule:
      interval: "daily" # Options: "daily", "weekly", "monthly"
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore"
      include-scope: true
    groups:
      npm_and_yarn:
        patterns:
          - "*"
        update-types:
          - "security"
    ignore:
      - dependency-name: "some-package"
        versions: [">=99.0.0"]
