name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-and-analyze:
    name: Lint & Codacy
    runs-on: ubuntu-22.04
    environment:
      name: megs_env
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint (JS/CSS/HTML)
        run: npm run lint

      - name: Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          tool: eslint
          upload: true
          verbose: true